(function(){
const token=new URLSearchParams(location.search).get('token')||'';const stage=document.getElementById('stage'),status=document.getElementById('status'),title=document.getElementById('title');let version='',current=-1,timer=null;
const asset=ref=>'/api/apps/presentations/remote/'+encodeURIComponent(token)+'/assets?ref='+encodeURIComponent(ref);
function position(n,e,c){n.style.left=(e.x/c.width*100)+'%';n.style.top=(e.y/c.height*100)+'%';n.style.width=(e.width/c.width*100)+'%';n.style.height=(e.height/c.height*100)+'%';n.style.zIndex=String(e.zIndex||0);if(e.rotation)n.style.transform='rotate('+e.rotation+'deg)';const a=e.animation||{};if(a.type&&a.type!=='none'){n.style.animation=(a.type==='zoom'?'fade':a.type)+' '+(a.durationMs||500)+'ms ease '+(a.delayMs||0)+'ms both'}}
function node(tag,cls){const n=document.createElement(tag);n.className='el '+cls;return n}
function text(e,c){const n=node('div','text'),s=e.style||{};n.textContent=e.content&&e.content.text||'';n.style.fontFamily=s.fontFamily||'Microsoft YaHei';n.style.fontWeight=String(s.fontWeight||400);n.style.fontSize=Math.max(8,(s.fontSize||18)/c.width*window.innerWidth)+'px';n.style.color=s.color||'#1f2937';n.style.textAlign=s.align||'left';n.style.lineHeight=String(s.lineHeight||1.35);n.style.padding=(s.padding||0)+'px';position(n,e,c);return n}
function shape(e,c){const n=node('div','shape'),s=e.style||{};n.style.background=s.fill||'#fff';n.style.borderColor=s.stroke||'#cbd5e1';n.style.borderWidth=(s.strokeWidth||1)+'px';n.style.borderRadius=e.shapeType==='ellipse'?'50%':(s.radius||0)+'px';n.style.opacity=String(s.opacity==null?1:s.opacity);position(n,e,c);return n}
function image(e,c){const n=node('div','image');n.style.backgroundImage='url("'+asset(e.assetRef)+'")';n.style.backgroundSize=e.fit==='contain'?'contain':e.fit==='stretch'?'100% 100%':'cover';n.style.backgroundRepeat='no-repeat';n.style.opacity=String(e.opacity==null?1:e.opacity);position(n,e,c);return n}
function diagram(e,c){const n=node('div','diagram'+(e.diagramType==='hierarchy'?' vertical':'')),s=e.style||{},items=e.items||[];items.forEach((v,i)=>{const chip=document.createElement('span');chip.textContent=v;chip.style.background=s.fill||'#eff6ff';chip.style.borderColor=s.stroke||'#2563eb';chip.style.color=s.textColor||'#1e3a8a';n.appendChild(chip);if(i<items.length-1){const a=document.createElement('i');a.textContent=e.diagramType==='hierarchy'?'↓':'→';n.appendChild(a)}});position(n,e,c);return n}
function media(e,c){const n=node('div','media');if(e.mediaType==='video'){const v=document.createElement('video');v.src=asset(e.assetRef);v.controls=e.showControls!==false;v.loop=!!e.loop;v.autoplay=!!e.autoPlay;n.appendChild(v)}else{const a=document.createElement('audio');a.src=asset(e.assetRef);a.controls=e.showControls!==false;a.loop=!!e.loop;a.autoplay=!!e.autoPlay;n.appendChild(a)}position(n,e,c);return n}
function attachment(e,c){const n=node('div','attachment');n.textContent='📎 '+(e.filename||'附件');position(n,e,c);return n}
function table(e,c){const n=node('div','table'),rows=[e.columns||[],...(e.rows||[])],s=e.style||{};rows.forEach((r,i)=>{const row=document.createElement('div');row.className='table-row';r.forEach(v=>{const cell=document.createElement('div');cell.className='cell';cell.textContent=v;cell.style.background=i===0?(s.headerFill||'#1769aa'):(s.cellFill||'#fff');cell.style.color=i===0?(s.headerColor||'#fff'):(s.cellColor||'#1f2937');row.appendChild(cell)});n.appendChild(row)});position(n,e,c);return n}
function chart(e,c){const n=node('div','chart'),vals=(e.data&&e.data.rows||[]).map(r=>Number(r[1])||0),m=Math.max(1,...vals.map(v=>Math.abs(v))),colors=e.options&&e.options.colors||['#2563eb'];vals.forEach((v,i)=>{const b=document.createElement('i');b.style.height=Math.max(4,Math.abs(v)/m*100)+'%';b.style.background=colors[i%colors.length];n.appendChild(b)});position(n,e,c);return n}
function render(remote){const c=remote.content,s=c.slides[remote.currentSlideIndex];if(!s)return;title.textContent=remote.title+' · 第 '+(remote.currentSlideIndex+1)+' / '+c.slides.length+' 页';stage.replaceChildren();stage.style.background=s.background&&s.background.fill||'#fff';stage.style.backgroundImage=s.background&&s.background.imageAssetRef?'url("'+asset(s.background.imageAssetRef)+'")':'';stage.style.backgroundSize='cover';(s.elements||[]).filter(e=>e.visible!==false).sort((a,b)=>(a.zIndex||0)-(b.zIndex||0)).forEach(e=>{let n;if(e.type==='text')n=text(e,c);else if(e.type==='shape')n=shape(e,c);else if(e.type==='image')n=image(e,c);else if(e.type==='diagram')n=diagram(e,c);else if(e.type==='media')n=media(e,c);else if(e.type==='attachment')n=attachment(e,c);else if(e.type==='table')n=table(e,c);else if(e.type==='chart')n=chart(e,c);if(n)stage.appendChild(n)});stage.classList.remove('fade');void stage.offsetWidth;stage.classList.add('fade')}
async function poll(){if(!token){status.textContent='缺少远程演示令牌';return}try{const r=await fetch('/api/apps/presentations/remote/'+encodeURIComponent(token)+'/state',{cache:'no-store'}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'远程会话不可用');const remote=data.remote;status.textContent='已连接 · 链接有效至 '+new Date(remote.expiresAt).toLocaleTimeString('zh-CN',{hour12:false});if(remote.version!==version||remote.currentSlideIndex!==current){version=remote.version;current=remote.currentSlideIndex;render(remote)}}catch(e){status.textContent=e.message||'远程会话已断开';clearInterval(timer)}}
poll();timer=setInterval(poll,800);document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll()});
})();
