const nodeGlobals = {
    AbortController: 'readonly',
    AbortSignal: 'readonly',
    Buffer: 'readonly',
    URL: 'readonly',
    URLSearchParams: 'readonly',
    __dirname: 'readonly',
    __filename: 'readonly',
    clearInterval: 'readonly',
    clearTimeout: 'readonly',
    console: 'readonly',
    exports: 'readonly',
    module: 'readonly',
    process: 'readonly',
    require: 'readonly',
    setImmediate: 'readonly',
    setInterval: 'readonly',
    setTimeout: 'readonly'
};

const browserGlobals = {
    Blob: 'readonly',
    CSS: 'readonly',
    DOMPurify: 'readonly',
    FileReader: 'readonly',
    FormData: 'readonly',
    Headers: 'readonly',
    AbortController: 'readonly',
    AbortSignal: 'readonly',
    File: 'readonly',
    Image: 'readonly',
    Intl: 'readonly',
    TextDecoder: 'readonly',
    URL: 'readonly',
    alert: 'readonly',
    caches: 'readonly',
    clearTimeout: 'readonly',
    clearInterval: 'readonly',
    confirm: 'readonly',
    console: 'readonly',
    document: 'readonly',
    Event: 'readonly',
    EventSource: 'readonly',
    fetch: 'readonly',
    getComputedStyle: 'readonly',
    hljs: 'readonly',
    katex: 'readonly',
    localStorage: 'readonly',
    location: 'readonly',
    marked: 'readonly',
    navigator: 'readonly',
    Node: 'readonly',
    NodeFilter: 'readonly',
    requestAnimationFrame: 'readonly',
    ResizeObserver: 'readonly',
    self: 'readonly',
    sessionStorage: 'readonly',
    setTimeout: 'readonly',
    setInterval: 'readonly',
    Request: 'readonly',
    URLSearchParams: 'readonly',
    window: 'readonly',
    XMLHttpRequest: 'readonly',
    API_BASE: 'readonly',
    APP_COPYRIGHT: 'readonly',
    APP_NAME: 'readonly',
    APP_VERSION: 'readonly',
    PivotSafeHtml: 'readonly',
    Pivot: 'readonly',
    appendMessage: 'readonly',
    apiFetch: 'readonly',
    authFetch: 'readonly',
    authHeaders: 'readonly',
    checkLogin: 'readonly',
    closeModal: 'readonly',
    closeModelModal: 'readonly',
    closePromptModal: 'readonly',
    closeUserModal: 'readonly',
    closeInputPrompt: 'readonly',
    createSession: 'readonly',
    deleteSession: 'readonly',
    describeSelectorModel: 'readonly',
    downloadFileByFetch: 'readonly',
    editSessionTags: 'readonly',
    encodeActionArg: 'readonly',
    escapeCsvValue: 'readonly',
    exportSession: 'readonly',
    currentAbortController: 'writable',
    currentSessionId: 'writable',
    currentUser: 'writable',
    escapeAttrValue: 'readonly',
    escapeChatStatusHtml: 'readonly',
    escapeCodeHtml: 'readonly',
    escapeHtml: 'readonly',
    formatChatCompactDateTime: 'readonly',
    formatChatDateTime: 'readonly',
    formatDateToCN: 'readonly',
    formatModelCapabilities: 'readonly',
    formatTokenAmount: 'readonly',
    formatTokenCount: 'readonly',
    formatTokenInputValue: 'readonly',
    formatSessionGroupDate: 'readonly',
    formatSessionListTime: 'readonly',
    getPermissionLabel: 'readonly',
    getPermissionTier: 'readonly',
    handleUnauthorized: 'readonly',
    ICONS: 'readonly',
    isAdminUser: 'readonly',
    isSuperAdminUser: 'readonly',
    loadApiCallLogs: 'readonly',
    loadApiKeys: 'readonly',
    loadAttachments: 'readonly',
    loadDetails: 'readonly',
    loadLogs: 'readonly',
    loadModels: 'readonly',
    loadMonitorSummary: 'readonly',
    loadOpsSummary: 'readonly',
    loadPrompts: 'readonly',
    loadReport: 'readonly',
    loadSessions: 'readonly',
    loadStats: 'readonly',
    loadUserRecordMessages: 'readonly',
    loadUsers: 'readonly',
    pageState: 'writable',
    parseTokenAmount: 'readonly',
    pendingAttachments: 'writable',
    refreshModelSelector: 'readonly',
    rememberThoughtStateBeforeRender: 'readonly',
    renderAiMessage: 'readonly',
    renderAttachmentPreviews: 'readonly',
    renderMarkdown: 'readonly',
    renderPagination: 'readonly',
    renderTableMessage: 'readonly',
    resetModelForm: 'readonly',
    resetPromptForm: 'readonly',
    resetUserForm: 'readonly',
    restoreThoughtStateAfterRender: 'readonly',
    resizeUserInput: 'readonly',
    selectedModel: 'writable',
    selectSession: 'readonly',
    sendMessage: 'readonly',
    setCsrfToken: 'readonly',
    showApp: 'readonly',
    showConfirm: 'readonly',
    showToast: 'readonly',
    stripInternalReferenceText: 'readonly',
    toggleArchiveSession: 'readonly',
    togglePinSession: 'readonly',
    renameSession: 'readonly'
};

const chatBundleGlobals = Object.fromEntries([
    'activateChatMcpToggle',
    'activeAgentWorkflowId',
    'AGENT_WORKFLOW_DRAFT_KEY',
    'AGENT_WORKFLOW_SAVED_KEY',
    'agentEscape',
    'agentEscapeAttr',
    'agentShortText',
    'agentWorkflowDraftDescription',
    'agentWorkflowDraftName',
    'agentWorkflowPickerQuery',
    'agentWorkflowsCache',
    'attachmentBelongsToSession',
    'autoLayout',
    'bindMcpFormControls',
    'buildNodeToolDisplay',
    'buildToolInputTemplate',
    'buildWizardDependencyNodes',
    'buildWizardFieldSuggestions',
    'buildWizardGroupCountSql',
    'caf',
    'callWizardTool',
    'clampDependsOn',
    'clearPendingAttachments',
    'cloneDagInput',
    'closeAgentDagNodeDrawer',
    'columnNameFromRow',
    'createBrowserSseParser',
    'createDagInspectorController',
    'createDagInteractionController',
    'createDagRenderController',
    'createDagWizardController',
    'createDagWizardStatsController',
    'cssEscape',
    'currentWorkflowMatchesSelected',
    'dagEditorInstance',
    'dagEscapeAttr',
    'dagEscapeHtml',
    'databaseConnectionIdFromToolValue',
    'databaseConnectionInputValue',
    'databaseConnectionLabel',
    'databaseConnectionsFromTool',
    'databaseToolConnectionOptions',
    'databaseWizardConnections',
    'DEFAULT_VIEW_SCALE',
    'defaultLlmInput',
    'defaultWorkflowModelId',
    'describeMonitorRoute',
    'ensureChatMcpConsent',
    'ensureDefaults',
    'ensureLlmNodeInput',
    'syncLlmOutputContract',
    'ensureSessionTagTools',
    'estimateStreamingTokenCount',
    'FIELD_DESCRIPTION_OVERRIDES',
    'FIELD_LABEL_OVERRIDES',
    'FIELD_PLACEHOLDER_OVERRIDES',
    'fieldUsageHint',
    'findPreferredTool',
    'flushOut',
    'formatBytes',
    'formatDuration',
    'formatHealthStatus',
    'formatMaintenanceTime',
    'formatMetricNumber',
    'formatObservabilityDuration',
    'formatWizardFieldValue',
    'friendlyEnumOptionLabel',
    'friendlyFieldDescription',
    'friendlyFieldLabel',
    'friendlyFieldPlaceholder',
    'friendlySchemaTypeLabel',
    'friendlyToolTitle',
    'getAgentWorkflowText',
    'getDisplayContent',
    'getToolSchema',
    'isChatToolEnabled',
    'isDatabaseConnectionField',
    'isKnownToolValue',
    'isLlmNode',
    'isMessageContainerNearBottom',
    'isMessageContentInDocument',
    'isTextualSchemaField',
    'isVisualSqlQueryTool',
    'keepLatestCodeBlockPinned',
    'keepMessageContainerPinnedToBottom',
    'llmNodeModel',
    'llmNodes',
    'loadAgentWorkflows',
    'loadSessionSearchResults',
    'loadSessionTagSummary',
    'loadSettings',
    'loadTabData',
    'makeSvgEl',
    'mcpBuiltinServices',
    'mcpBuiltinToolLabels',
    'mcpCallLogsCache',
    'mcpCleanServiceName',
    'mcpDbDefaultPorts',
    'mcpDbToolLabels',
    'mcpEscape',
    'mcpExternalServiceCatalog',
    'mcpFallbackToolsForServer',
    'mcpFormEl',
    'mcpIsLocalDeviceServerId',
    'mcpLocalAuthorizedFallbackTools',
    'mcpLocalDeviceServer',
    'mcpMetadataForType',
    'mcpOwnerLabel',
    'mcpPersonalBuiltinServices',
    'mcpServerIdFromTool',
    'mcpServersCache',
    'mcpServiceCatalog',
    'mcpShouldShowOwner',
    'mcpSystemServices',
    'mcpToolDescription',
    'mcpToolPreviewText',
    'mcpToolPrompt',
    'mcpToolsCache',
    'mcpToolsForServer',
    'mcpToolTitle',
    'MIN_CONTENT_HEIGHT',
    'MIN_CONTENT_WIDTH',
    'mountAgentDagEditor',
    'NODE_GAP_X',
    'NODE_HEIGHT',
    'NODE_WIDTH',
    'normalizeFieldKey',
    'normalizePivotChartSpec',
    'normalizeSchemaType',
    'observabilitySeverityLabels',
    'observabilityTypeLabels',
    'PADDING',
    'parseAgentWorkflowText',
    'publishSelectedAgentWorkflow',
    'raf',
    'readChatErrorMessage',
    'readJson',
    'render',
    'renderAgentWorkflowLifecycle',
    'renderDagToolbar',
    'renderDatabaseAssistPanel',
    'renderFinalAssistantStats',
    'renderInputSummary',
    'renderMcpCardTags',
    'renderMcpSection',
    'renderMcpServiceCard',
    'renderMonitorEndpointLists',
    'renderPivotCharts',
    'renderSelectedToolMeta',
    'renderStreamingAssistantContent',
    'renderToolOptions',
    'renderToolSchemaHint',
    'renderTrendChart',
    'renderWizardField',
    'renderWizardFieldSources',
    'renderVisualSqlBuilder',
    'resolveStreamInterval',
    'resolveToolForNode',
    'mountVisualSqlBuilder',
    'runBatchTagAction',
    'safeAlias',
    'SCALE_MAX',
    'SCALE_MIN',
    'selectedAgentWorkflow',
    'selectedDatabaseConnectionId',
    'selectedSessionIds',
    'serialize',
    'sessionBatchMode',
    'sessionMenuData',
    'sessionSearchArchived',
    'sessionSearchTimer',
    'setMcpEditTitle',
    'setMcpSourceType',
    'setSessionBatchMode',
    'shouldAutoEnableMcpForPrompt',
    'sidebarState',
    'splitAssistantStreamDelta',
    'STREAM_LOCAL_REPLAY_INTERVAL_MS',
    'STREAM_LOCAL_REPLAY_MAX_WAIT_MS',
    'summarizeAgentDagSpec',
    'SVG_NS',
    'syncPendingAttachmentsGlobal',
    'tableNameFromRow',
    'TOOL_FIELD_DESCRIPTION_OVERRIDES',
    'TOOL_FIELD_LABEL_OVERRIDES',
    'TOOL_FIELD_PLACEHOLDER_OVERRIDES',
    'toolShortName',
    'toolValue',
    'uniqueId',
    'updateAgentWorkflowRunUi',
    'updateSessionBatchBar',
    'userInput',
    'validateLlmNodePlacement',
    'workflowModelOptions',
    'writeAgentWorkflowText',
    'writeJson'
].map(name => [name, 'readonly']));

// apps-workbench.js 按工作流拆分为 apps-workbench-core/editor/proofread/ai/rewrite/rag.js
// 后，这些原本同文件内的顶层声明变为跨文件共享的全局，需在此登记（与 dag-*/mcp-* 拆分同理）。
const appsWorkbenchGlobals = {
    // 跨文件可变状态（全局脚本共享）
    officialWritingState: 'writable',
    officialWritingLibrary: 'writable',
    officialWritingUiState: 'writable',
    officialWritingAiBusy: 'writable',
    officialWritingAiBusyLabel: 'writable',
    officialWritingProgrammaticTextUpdate: 'writable',
    officialWritingAnalysisDebounceTimer: 'writable',
    officialWritingDiffState: 'writable',
    // 跨文件函数 / 常量引用
    ...Object.fromEntries([
        'OFFICIAL_WRITING_COMMENT_LIMIT',
        'OFFICIAL_WRITING_DEFAULT_FORM_STATE',
        'OFFICIAL_WRITING_DEFAULT_META',
        'OFFICIAL_WRITING_DRAWER_META',
        'OFFICIAL_WRITING_HISTORY_LIMIT',
        'OFFICIAL_WRITING_MATERIAL_TAB_TO_SOURCE',
        'OFFICIAL_WRITING_META_FIELD_IDS',
        'OFFICIAL_WRITING_MODES',
        'OFFICIAL_WRITING_REQUIREMENT_PLACEHOLDERS',
        'OFFICIAL_WRITING_SUGGESTION_LIMIT',
        'OFFICIAL_WRITING_TEMPLATES',
        'OFFICIAL_WRITING_TYPE_TO_TEMPLATE_KEY',
        'PIVOT_APP_REGISTRY',
        'addOfficialWritingComment',
        'addOfficialWritingSuggestion',
        'applyOfficialWritingDiffResult',
        'applyOfficialWritingLeftRailState',
        'applyOfficialWritingViewMode',
        'applySelectionAction',
        'applySuggestionAction',
        'buildOfficialWritingDocxBlob',
        'buildOfficialWritingExportHtml',
        'buildOfficialWritingFooterLines',
        'buildOfficialWritingHeaderLines',
        'captureSelection',
        'classifyOfficialWritingParagraph',
        'closeOfficialWritingCommandMenu',
        'closeOfficialWritingCreateDialog',
        'closeOfficialWritingDiffModal',
        'closeOfficialWritingDrawer',
        'closeOfficialWritingDraftDialog',
        'closeOfficialWritingMaterialModal',
        'closeOfficialWritingMaterialEditor',
        'compactTextPreview',
        'compareOfficialWritingVersions',
        'clearOfficialWritingMaterialEditor',
        'copyOfficialWritingPrompt',
        'createOfficialWritingDoc',
        'createOfficialWritingState',
        'deleteOfficialWritingComment',
        'deleteOfficialWritingDoc',
        'downloadOfficialWritingBlob',
        'downloadOfficialWritingFile',
        'ensureOfficialWritingRagCollections',
        'escapeAppsHtml',
        'exportOfficialWriting',
        'exportOfficialWritingBackup',
        'exportOfficialWritingText',
        'flushOfficialWritingAnalysis',
        'generateOfficialWritingDocId',
        'generateOfficialWritingSuggestion',
        'getActiveOfficialWritingDoc',
        'getBestOfficialWritingSelection',
        'getOfficialWritingComplianceRisks',
        'getOfficialWritingDocType',
        'getOfficialWritingInsertionPoint',
        'getOfficialWritingMaterialSegments',
        'getOfficialWritingMaterialSource',
        'getOfficialWritingMetaForExport',
        'getOfficialWritingMode',
        'getOfficialWritingRequirements',
        'getOfficialWritingStandard',
        'getOfficialWritingStandardRules',
        'getOfficialWritingSurface',
        'getOfficialWritingSurfaceSelection',
        'getOfficialWritingTargetFromTextarea',
        'getOfficialWritingTextarea',
        'getOfficialWritingWorkspaceSummary',
        'getStoredAppsActiveApp',
        'handleOfficialWritingReviewSuggestions',
        'handleOfficialWritingSurfaceBlur',
        'handleOfficialWritingSurfaceInput',
        'handleOfficialWritingSurfaceKeydown',
        'handleOfficialWritingSurfacePaste',
        'hydrateOfficialWritingForm',
        'hydrateOfficialWritingMetaForm',
        'jumpOfficialWritingRange',
        'loadOfficialWritingVersion',
        'markOfficialWritingProofreadChecked',
        'normalizeOfficialWritingIndex',
        'normalizeOfficialWritingMeta',
        'normalizeOfficialWritingMode',
        'officialWritingRedoStack',
        'officialWritingUndoStack',
        'openOfficialWritingCreateDialog',
        'openOfficialWritingDrawer',
        'openOfficialWritingDraftDialog',
        'openOfficialWritingMaterialModal',
        'openOfficialWritingMaterialEditor',
        'openRegisteredApp',
        'pushOfficialWritingUndoSnapshot',
        'rememberOfficialWritingSelection',
        'renameOfficialWritingDoc',
        'renderOfficialWritingCompliance',
        'renderOfficialWritingDiffRows',
        'renderOfficialWritingDocList',
        'renderOfficialWritingProofread',
        'renderOfficialWritingReferences',
        'renderOfficialWritingMaterials',
        'renderOfficialWritingStats',
        'renderOfficialWritingSuggestions',
        'renderOfficialWritingSurfaces',
        'renderOfficialWritingWorkspace',
        'replaceTextareaRange',
        'requestOfficialWritingAi',
        'resetOfficialWritingForm',
        'resizeOfficialWritingDraftPage',
        'runOfficialWritingMode',
        'runOfficialWritingProofread',
        'runOfficialWritingReview',
        'runOfficialWritingStreamRewrite',
        'saveOfficialWritingMaterialEditor',
        'saveOfficialWritingState',
        'saveOfficialWritingVersion',
        'scheduleOfficialWritingAnalysis',
        'sendOfficialWritingToChat',
        'setOfficialWritingAiBusy',
        'setOfficialWritingCreateDialogError',
        'setOfficialWritingDraftDialogError',
        'setOfficialWritingDiffRowAccepted',
        'setOfficialWritingMaterialSource',
        'setOfficialWritingMaterialTab',
        'setOfficialWritingScreen',
        'setOfficialWritingTextareaValue',
        'setStoredAppsActiveApp',
        'setAppsTitle',
        'setText',
        'setTextareaSelection',
        'showDataAnalysisAppFromRegistry',
        'showAppsHome',
        'showOfficialWritingApp',
        'showOfficialWritingLibrary',
        'submitOfficialWritingCreateDialog',
        'submitOfficialWritingDraftDialog',
        'splitOfficialWritingParagraphs',
        'switchOfficialWritingDoc',
        'syncOfficialWritingMaterialEditor',
        'syncOfficialWritingMaterialEditorStats',
        'syncOfficialWritingMetaFromInputs',
        'syncOfficialWritingSourceToDraft',
        'syncOfficialWritingAiIndicators',
        'syncOfficialWritingStateFromInputs',
        'toggleOfficialWritingDrawer',
        'toggleOfficialWritingLeftRail',
        'updateOfficialWritingSurfaceVisibility',
        'updateOfficialWritingUndoRedoButtons',
    ].map(name => [name, 'readonly']))
};

module.exports = [
    {
        ignores: [
            'node_modules/**',
            '.codex-tmp/**',
            'data/**',
            'logs/**',
            'uploads/**',
            'dist-electron/**',
            'client/common/vendor/**'
        ]
    },
    {
        files: ['server/**/*.js', 'scripts/**/*.js', 'tests/**/*.js', 'desktop/**/*.js', 'eslint.config.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'commonjs',
            globals: nodeGlobals
        },
        rules: {
            'no-undef': 'error',
            'no-unused-vars': ['warn', {
                argsIgnorePattern: '^_',
                caughtErrors: 'none',
                varsIgnorePattern: '^_'
            }],
            // 抓真实 bug 的低误报规则
            'no-cond-assign': 'error',
            'no-dupe-keys': 'error',
            'no-dupe-args': 'error',
            'no-unreachable': 'error',
            'no-constant-condition': ['error', { checkLoops: false }],
            'no-func-assign': 'error',
            'use-isnan': 'error',
            'valid-typeof': 'error',
            'no-self-assign': 'error',
            'no-unsafe-negation': 'error',
            'require-atomic-updates': 'off'
        }
    },
    {
        files: ['client/**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'script',
            globals: {
                ...browserGlobals,
                ...chatBundleGlobals,
                ...appsWorkbenchGlobals
            }
        },
        rules: {
            'no-undef': 'error',
            'no-unused-vars': ['warn', {
                argsIgnorePattern: '^_',
                caughtErrors: 'none',
                vars: 'local',
                varsIgnorePattern: '^_'
            }],
            // 抓真实 bug 的低误报规则
            'no-cond-assign': 'error',
            'no-dupe-keys': 'error',
            'no-dupe-args': 'error',
            'no-unreachable': 'error',
            'no-constant-condition': ['error', { checkLoops: false }],
            'no-func-assign': 'error',
            'use-isnan': 'error',
            'valid-typeof': 'error',
            'no-self-assign': 'error',
            'no-unsafe-negation': 'error'
        }
    }
];
