const nodeGlobals = {
    Buffer: 'readonly',
    URL: 'readonly',
    __dirname: 'readonly',
    __filename: 'readonly',
    clearInterval: 'readonly',
    clearTimeout: 'readonly',
    console: 'readonly',
    exports: 'readonly',
    module: 'readonly',
    process: 'readonly',
    require: 'readonly',
    setImmediate: 'readonly',
    setInterval: 'readonly',
    setTimeout: 'readonly'
};

const browserGlobals = {
    Blob: 'readonly',
    DOMPurify: 'readonly',
    FileReader: 'readonly',
    FormData: 'readonly',
    Headers: 'readonly',
    AbortController: 'readonly',
    File: 'readonly',
    Image: 'readonly',
    Intl: 'readonly',
    TextDecoder: 'readonly',
    URL: 'readonly',
    alert: 'readonly',
    caches: 'readonly',
    clearTimeout: 'readonly',
    clearInterval: 'readonly',
    confirm: 'readonly',
    console: 'readonly',
    document: 'readonly',
    Event: 'readonly',
    fetch: 'readonly',
    hljs: 'readonly',
    katex: 'readonly',
    localStorage: 'readonly',
    location: 'readonly',
    marked: 'readonly',
    navigator: 'readonly',
    requestAnimationFrame: 'readonly',
    self: 'readonly',
    sessionStorage: 'readonly',
    setTimeout: 'readonly',
    setInterval: 'readonly',
    Request: 'readonly',
    URLSearchParams: 'readonly',
    window: 'readonly',
    XMLHttpRequest: 'readonly',
    API_BASE: 'readonly',
    APP_COPYRIGHT: 'readonly',
    APP_NAME: 'readonly',
    APP_VERSION: 'readonly',
    PivotSafeHtml: 'readonly',
    appendMessage: 'readonly',
    apiFetch: 'readonly',
    authFetch: 'readonly',
    authHeaders: 'readonly',
    checkLogin: 'readonly',
    closeModal: 'readonly',
    closeModelModal: 'readonly',
    closePromptModal: 'readonly',
    closeUserModal: 'readonly',
    closeInputPrompt: 'readonly',
    createSession: 'readonly',
    deleteSession: 'readonly',
    describeSelectorModel: 'readonly',
    downloadFileByFetch: 'readonly',
    editSessionTags: 'readonly',
    encodeActionArg: 'readonly',
    escapeCsvValue: 'readonly',
    exportSession: 'readonly',
    currentAbortController: 'writable',
    currentSessionId: 'writable',
    currentUser: 'writable',
    escapeAttrValue: 'readonly',
    escapeChatStatusHtml: 'readonly',
    escapeCodeHtml: 'readonly',
    escapeHtml: 'readonly',
    formatChatCompactDateTime: 'readonly',
    formatChatDateTime: 'readonly',
    formatDateToCN: 'readonly',
    formatModelCapabilities: 'readonly',
    formatTokenAmount: 'readonly',
    formatTokenCount: 'readonly',
    formatTokenInputValue: 'readonly',
    formatSessionGroupDate: 'readonly',
    formatSessionListTime: 'readonly',
    handleUnauthorized: 'readonly',
    ICONS: 'readonly',
    loadApiCallLogs: 'readonly',
    loadApiKeys: 'readonly',
    loadAttachments: 'readonly',
    loadDetails: 'readonly',
    loadLogs: 'readonly',
    loadModels: 'readonly',
    loadMonitorSummary: 'readonly',
    loadOpsSummary: 'readonly',
    loadPrompts: 'readonly',
    loadReport: 'readonly',
    loadSessions: 'readonly',
    loadStats: 'readonly',
    loadUserRecordMessages: 'readonly',
    loadUsers: 'readonly',
    pageState: 'writable',
    parseTokenAmount: 'readonly',
    pendingAttachments: 'writable',
    refreshModelSelector: 'readonly',
    rememberThoughtStateBeforeRender: 'readonly',
    renderAiMessage: 'readonly',
    renderAttachmentPreviews: 'readonly',
    renderMarkdown: 'readonly',
    renderPagination: 'readonly',
    renderTableMessage: 'readonly',
    resetModelForm: 'readonly',
    resetPromptForm: 'readonly',
    resetUserForm: 'readonly',
    restoreThoughtStateAfterRender: 'readonly',
    resizeUserInput: 'readonly',
    selectedModel: 'writable',
    selectSession: 'readonly',
    sendMessage: 'readonly',
    setCsrfToken: 'readonly',
    showApp: 'readonly',
    showConfirm: 'readonly',
    showToast: 'readonly',
    stripInternalReferenceText: 'readonly',
    toggleArchiveSession: 'readonly',
    togglePinSession: 'readonly',
    renameSession: 'readonly'
};

module.exports = [
    {
        ignores: [
            'node_modules/**',
            'data/**',
            'logs/**',
            'uploads/**',
            'client/common/vendor/**'
        ]
    },
    {
        files: ['server/**/*.js', 'scripts/**/*.js', 'tests/**/*.js', 'eslint.config.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'commonjs',
            globals: nodeGlobals
        },
        rules: {
            'no-undef': 'error',
            'no-unused-vars': ['warn', {
                argsIgnorePattern: '^_',
                caughtErrors: 'none',
                varsIgnorePattern: '^_'
            }]
        }
    },
    {
        files: ['client/**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'script',
            globals: browserGlobals
        },
        rules: {
            'no-undef': 'error',
            'no-unused-vars': ['warn', {
                argsIgnorePattern: '^_',
                caughtErrors: 'none',
                varsIgnorePattern: '^_'
            }]
        }
    }
];
