/**
 * server/db/schema/comments.js
 * 数据库表级与字段级中文元数据注释字典（全量 79 张业务表与全字段 100% 完整覆盖）
 *
 * 用于在 PostgreSQL 中执行 COMMENT ON TABLE / COMMENT ON COLUMN，
 * 方便 DBA 运维、Navicat / DBeaver / DataGrip 等数据库客户端直观查阅数据字典。
 */

const TABLE_COMMENTS = {
    "app_meta": "系统全局元数据与运行状态标记表",
    "schema_migrations": "版本化数据库迁移执行记录表",
    "app_settings": "系统级全局参数与业务运行配置表",
    "user_settings": "用户个人偏好设置与个性化配置表",
    "audit_logs": "全局安全审计日志与用户操作行为轨迹表",
    "api_call_logs": "外部 API 与模型调用审计日志表",
    "observability_events": "系统可观测性监控与性能指标事件表",
    "users": "系统用户主表（包含账号、身份、权限角色及状态）",
    "refresh_tokens": "用户登录刷新令牌与会话凭证表",
    "api_keys": "OpenAI 协议兼容的对外开放 API Key 表",
    "sessions": "用户聊天对话会话主表",
    "messages": "会话内聊天消息明细表（含用户提问、助手回复与推理思考）",
    "attachments": "会话消息上传的附件元数据表（图片、文档等）",
    "prompts": "提示词模板与快捷角色指令库",
    "announcements": "系统全员公告与通知发布主表",
    "announcement_reads": "全员公告用户已读状态记录表",
    "models": "接入的 LLM 大语言模型与多模态模型配置表",
    "model_usage_events": "模型 Token 用量与计费统计事件表",
    "memories": "用户专属长期记忆库（事实、偏好、习惯与技能）",
    "memory_extraction_jobs": "长期记忆异步抽取与合并治理任务表",
    "knowledge_collections": "企业知识库集合（合集）分类表",
    "knowledge_docs": "知识库文档主表（解析状态与源文件引用）",
    "knowledge_chunks": "知识库切片分块与稠密向量索引表",
    "knowledge_doc_tags": "知识库文档与标签关联映射表",
    "knowledge_tags": "知识库业务标签定义字典表",
    "rag_feedback": "RAG 问答效果用户点赞点踩反馈表",
    "rag_debug_queries": "RAG 检索调试历史与得分分析记录表",
    "knowledge_entities": "知识图谱实体主表（概念、术语、机构等）",
    "knowledge_entity_mentions": "知识图谱实体在文档分块中的提及引用表",
    "knowledge_relations": "知识图谱实体间三元组关系表",
    "regulation_documents": "企业制度规范制度文档主表",
    "regulation_versions": "制度文档历史版本与生命周期管理表",
    "regulation_articles": "制度条款拆解细则与条款内容表",
    "regulation_article_links": "制度条款之间的上下游引用关联表",
    "regulation_aliases": "制度条款同义词与业务别名表",
    "regulation_article_annotations": "制度条款人工专家批注与解读表",
    "regulation_access_logs": "制度库用户查阅与访问审计日志表",
    "regulation_saved_searches": "用户制度检索收藏与常用查询条件表",
    "agent_runs": "智能体任务运行主表（包含目标、状态、预算与模式）",
    "agent_steps": "智能体单步执行记录表（规划、思考、工具调用与结果）",
    "agent_traces": "智能体分布式链路追踪 Trace 主表",
    "agent_trace_spans": "智能体链路 Span 明细表（阶段耗时与调用拓扑）",
    "agent_run_checkpoints": "智能体长时间运行状态快照与断点恢复 Checkpoint 表",
    "agent_eval_suites": "智能体自动化评测集定义主表",
    "agent_eval_cases": "智能体评测集测试用例明细表",
    "agent_eval_runs": "智能体评测执行批次运行表",
    "agent_eval_results": "智能体评测用例得分与指标明细表",
    "agent_templates": "智能体可复用预设模版与应用资产表",
    "agent_schedules": "智能体定时自动化调度任务表（Cron 触发器）",
    "agent_artifacts": "智能体执行生成的产物元数据表（文件、报告、图表）",
    "agent_artifact_versions": "智能体产物历史迭代版本表",
    "agent_dag_nodes": "智能体 DAG 编排节点执行状态与上下文表",
    "agent_approval_requests": "智能体高危工具人工审批请求表（Human-in-the-loop）",
    "agent_notifications": "智能体执行完成与告警系统通知表",
    "agent_workflows": "企业可视化工作流定义主表",
    "agent_workflow_versions": "工作流版本编排快照表（节点与连线 DAG 结构）",
    "agent_workflow_dependency_bindings": "工作流跨节点依赖与动态数据绑定表",
    "agent_workflow_triggers": "工作流外部事件与 Webhook 触发器表",
    "workflow_credentials": "工作流集成第三方系统安全凭证表（加密存储）",
    "organizations": "多租户企业组织机构主表",
    "teams": "企业部门与业务团队定义表",
    "team_members": "团队成员关系与团队内角色关联表",
    "resource_permissions": "细粒度资源访问控制策略表（ACL/RBAC）",
    "policy_objects": "企业安全与合规治理策略对象表",
    "deployment_provider_configs": "模型与算力部署服务商环境配置表",
    "capability_packages": "企业扩展功能包与能力单元配置表",
    "mcp_servers": "MCP（Model Context Protocol）外部服务节点配置表",
    "mcp_tool_cache": "MCP 动态暴露工具定义元数据缓存表",
    "mcp_call_logs": "MCP 工具实际调用入参、出参与延迟日志表",
    "mcp_database_connections": "MCP 关系型数据库连接源配置表",
    "mcp_builtin_configs": "系统内置 MCP 插件与扩展参数配置表",
    "document_files": "文档智能处理流水线原始文件存储表",
    "document_jobs": "文档解析、OCR 与结构化抽取异步作业表",
    "document_pages": "文档单页渲染图片与页面元数据表",
    "document_ocr_blocks": "文档 OCR 识别文本框与排版几何块表",
    "document_outputs": "文档处理最终结构化产物输出表（Markdown/JSON）",
    "document_reviews": "文档结构化内容人工校对与审核修正表",
    "analysis_datasets": "数据分析看板导入的数据集主表",
    "analysis_artifacts": "数据分析生成的图表视图与统计分析结果表"
};

const COLUMN_COMMENTS = {
    "app_meta": {
        "key": "唯一标识 Key",
        "value": "配置键值内容",
        "updated_at": "最后更新时间（东八区）"
    },
    "schema_migrations": {
        "id": "主键自增 ID / 唯一主键",
        "description": "详细描述说明",
        "applied_at": "迁移应用生效时间"
    },
    "app_settings": {
        "key": "唯一标识 Key",
        "value": "配置键值内容",
        "updated_at": "最后更新时间（东八区）",
        "updated_by": "最后更新人用户 ID（关联 users.id）"
    },
    "user_settings": {
        "user_id": "所属用户 ID（关联 users.id）",
        "key": "唯一标识 Key",
        "value": "配置键值内容",
        "updated_at": "最后更新时间（东八区）"
    },
    "users": {
        "id": "主键自增 ID / 唯一主键",
        "username": "登录用户名",
        "deleted_username": "users 表的 deleted_username 字段",
        "password_hash": "哈希加密密码密文",
        "nickname": "用户界面昵称",
        "unit": "所属业务单位/部门",
        "default_model_id": "users 表的 default_model_id 字段",
        "role": "角色标识（user/assistant/system/tool 等）",
        "status": "状态标识",
        "deleted_at": "软删除时间（为空表示正常有效）",
        "deleted_by_admin": "是否由管理员执行软删除（1:是, 0:否）",
        "last_login_at": "最后一次成功登录时间",
        "created_at": "记录创建时间（东八区）"
    },
    "sessions": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "title": "标题",
        "is_pinned": "是否置顶（1:是, 0:否）",
        "is_archived": "是否已归档（1:是, 0:否）",
        "tags": "关联标签列表（JSON/数组）",
        "system_prompt": "sessions 表的 system_prompt 字段",
        "deleted_at": "软删除时间（为空表示正常有效）",
        "deleted_by_user": "执行删除操作的用户 ID",
        "parent_session_id": "来源父会话 ID（分叉 Fork 源）",
        "forked_from_message_id": "分叉起点的消息 ID",
        "fork_root_session_id": "分叉根会话 ID",
        "fork_note": "会话分叉备注说明",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "messages": {
        "id": "主键自增 ID / 唯一主键",
        "session_id": "关联的会话 ID（关联 sessions.id）",
        "user_id": "所属用户 ID（关联 users.id）",
        "role": "角色标识（user/assistant/system/tool 等）",
        "content": "正文内容",
        "token_count": "Token 数量统计",
        "is_summary": "是否为摘要消息（1:是, 0:否）",
        "context_archived": "是否已在上下文中归档裁剪（1:是, 0:否）",
        "compressed_at": "上下文压缩时间",
        "model_id": "关联的模型 ID（关联 models.id）",
        "agent_run_id": "创建该助手消息的持久化 Agent 运行 ID",
        "cost_time": "执行耗时（毫秒）",
        "tokens_per_sec": "messages 表的 tokens_per_sec 字段",
        "deleted_at": "软删除时间（为空表示正常有效）",
        "deleted_by_user": "执行删除操作的用户 ID",
        "created_at": "记录创建时间（东八区）"
    },
    "memories": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "scope": "可见范围或作用域（public/unit/private/system）",
        "type": "类型标识",
        "content": "正文内容",
        "embedding": "向量表示数据（pgvector 向量）",
        "salience": "重要性得分（0.0~1.0）",
        "confidence": "置信度得分（0.0~1.0）",
        "source_session_id": "来源会话 ID",
        "source_message_ids": "来源消息 ID 列表（JSON）",
        "status": "状态标识",
        "last_used_at": "最后一次使用/命中时间",
        "expires_at": "过期失效时间",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "memory_extraction_jobs": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "session_id": "关联的会话 ID（关联 sessions.id）",
        "message_ids": "memory_extraction_jobs 表的 message_ids 字段",
        "model_id": "关联的模型 ID（关联 models.id）",
        "dedupe_key": "memory_extraction_jobs 表的 dedupe_key 字段",
        "status": "状态标识",
        "attempts": "已重试次数",
        "max_attempts": "最大允许重试次数",
        "locked_at": "任务加锁时间（防止并发争抢）",
        "last_error": "最后一次失败错误原因",
        "result": "memory_extraction_jobs 表的 result 字段",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）",
        "next_run_at": "预计下次调度执行时间",
        "completed_at": "执行完成时间"
    },
    "models": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "name": "名称",
        "url": "models 表的 url 字段",
        "api_key": "API 密钥凭证（加密存储）",
        "model_name": "models 表的 model_name 字段",
        "is_default": "是否为默认配置（1:是, 0:否）",
        "daily_token_limit": "models 表的 daily_token_limit 字段",
        "allowed_units": "允许访问的单位/部门白名单（JSON）",
        "status": "状态标识",
        "temperature": "models 表的 temperature 字段",
        "max_input_tokens": "models 表的 max_input_tokens 字段",
        "max_tokens": "models 表的 max_tokens 字段",
        "context_window_tokens": "models 表的 context_window_tokens 字段",
        "monitor_url": "models 表的 monitor_url 字段",
        "max_concurrent": "models 表的 max_concurrent 字段",
        "supports_vision": "models 表的 supports_vision 字段",
        "supports_reasoning": "models 表的 supports_reasoning 字段",
        "chat_thinking_enabled": "models 表的 chat_thinking_enabled 字段",
        "input_price_per_million": "models 表的 input_price_per_million 字段",
        "output_price_per_million": "models 表的 output_price_per_million 字段",
        "price_currency": "models 表的 price_currency 字段",
        "created_at": "记录创建时间（东八区）"
    },
    "audit_logs": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "action": "操作动作权限",
        "details": "详细信息明细",
        "ip_address": "客户端 IP 地址",
        "timestamp": "事件发生时间戳"
    },
    "knowledge_collections": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "name": "名称",
        "description": "详细描述说明",
        "scope": "可见范围或作用域（public/unit/private/system）",
        "allowed_units": "允许访问的单位/部门白名单（JSON）",
        "allowed_user_ids": "允许访问的用户 ID 白名单（JSON）",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）",
        "deleted_at": "软删除时间（为空表示正常有效）"
    },
    "knowledge_docs": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "collection_id": "所属知识库合集 ID（关联 knowledge_collections.id）",
        "name": "名称",
        "status": "状态标识",
        "is_enabled": "是否启用（1:是, 0:否）",
        "chunk_count": "分块切片总数量",
        "indexed_chunks": "已索引完成的分块数",
        "progress": "任务执行进度百分比（0~100）",
        "error_message": "异常报错信息",
        "processed_at": "数据处理完成时间",
        "updated_at": "最后更新时间（东八区）",
        "source_path": "源文件存储相对路径",
        "source_size": "源文件大小（字节）",
        "deleted_at": "软删除时间（为空表示正常有效）",
        "deleted_by_user": "执行删除操作的用户 ID",
        "created_at": "记录创建时间（东八区）"
    },
    "knowledge_chunks": {
        "id": "主键自增 ID / 唯一主键",
        "doc_id": "所属知识库文档 ID（关联 knowledge_docs.id）",
        "content": "正文内容",
        "search_content": "全文检索分词优化文本",
        "heading_path": "章节标题层级路径",
        "embedding": "向量表示数据（pgvector 向量）"
    },
    "knowledge_doc_tags": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "doc_id": "所属知识库文档 ID（关联 knowledge_docs.id）",
        "tag": "knowledge_doc_tags 表的 tag 字段",
        "created_at": "记录创建时间（东八区）"
    },
    "knowledge_tags": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "tag": "knowledge_tags 表的 tag 字段",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）",
        "deleted_at": "软删除时间（为空表示正常有效）"
    },
    "regulation_documents": {
        "id": "主键自增 ID / 唯一主键",
        "title": "标题",
        "category": "业务分类类别",
        "issuing_body": "发布机关/颁布部门",
        "jurisdiction": "适用管辖范围",
        "summary": "内容摘要总结",
        "status": "状态标识",
        "visibility": "regulation_documents 表的 visibility 字段",
        "current_version_id": "当前激活的版本 ID",
        "version_count": "regulation_documents 表的 version_count 字段",
        "article_count": "regulation_documents 表的 article_count 字段",
        "created_by_user": "regulation_documents 表的 created_by_user 字段",
        "updated_by_user": "regulation_documents 表的 updated_by_user 字段",
        "deleted_at": "软删除时间（为空表示正常有效）",
        "deleted_by_user": "执行删除操作的用户 ID",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "regulation_versions": {
        "id": "主键自增 ID / 唯一主键",
        "document_id": "所属文档 ID",
        "version_label": "regulation_versions 表的 version_label 字段",
        "source_name": "regulation_versions 表的 source_name 字段",
        "source_path": "源文件存储相对路径",
        "source_size": "源文件大小（字节）",
        "source_hash": "regulation_versions 表的 source_hash 字段",
        "source_format": "regulation_versions 表的 source_format 字段",
        "extracted_text": "regulation_versions 表的 extracted_text 字段",
        "summary": "内容摘要总结",
        "article_count": "regulation_versions 表的 article_count 字段",
        "uploaded_by_user": "regulation_versions 表的 uploaded_by_user 字段",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "regulation_articles": {
        "id": "主键自增 ID / 唯一主键",
        "document_id": "所属文档 ID",
        "version_id": "关联的工作流或制度版本 ID",
        "sort_order": "regulation_articles 表的 sort_order 字段",
        "article_label": "regulation_articles 表的 article_label 字段",
        "article_title": "regulation_articles 表的 article_title 字段",
        "content": "正文内容",
        "search_content": "全文检索分词优化文本",
        "heading_path": "章节标题层级路径",
        "status": "状态标识",
        "amended_date": "regulation_articles 表的 amended_date 字段",
        "embedding": "向量表示数据（pgvector 向量）",
        "created_at": "记录创建时间（东八区）"
    },
    "regulation_article_links": {
        "id": "主键自增 ID / 唯一主键",
        "document_id": "所属文档 ID",
        "version_id": "关联的工作流或制度版本 ID",
        "source_article_id": "regulation_article_links 表的 source_article_id 字段",
        "target_label": "regulation_article_links 表的 target_label 字段",
        "target_article_id": "regulation_article_links 表的 target_article_id 字段",
        "target_document_id": "regulation_article_links 表的 target_document_id 字段",
        "relation_type": "关系谓词类型",
        "confidence": "置信度得分（0.0~1.0）",
        "created_at": "记录创建时间（东八区）"
    },
    "regulation_aliases": {
        "id": "主键自增 ID / 唯一主键",
        "document_id": "所属文档 ID",
        "alias": "别名/简称",
        "normalized_alias": "regulation_aliases 表的 normalized_alias 字段",
        "is_primary": "regulation_aliases 表的 is_primary 字段",
        "created_at": "记录创建时间（东八区）"
    },
    "regulation_article_annotations": {
        "id": "主键自增 ID / 唯一主键",
        "article_id": "regulation_article_annotations 表的 article_id 字段",
        "user_id": "所属用户 ID（关联 users.id）",
        "content": "正文内容",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "regulation_access_logs": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "document_id": "所属文档 ID",
        "action": "操作动作权限",
        "detail": "regulation_access_logs 表的 detail 字段",
        "created_at": "记录创建时间（东八区）"
    },
    "regulation_saved_searches": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "name": "名称",
        "query": "regulation_saved_searches 表的 query 字段",
        "category": "业务分类类别",
        "jurisdiction": "适用管辖范围",
        "created_at": "记录创建时间（东八区）"
    },
    "rag_feedback": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "query": "rag_feedback 表的 query 字段",
        "chunk_id": "rag_feedback 表的 chunk_id 字段",
        "doc_name": "rag_feedback 表的 doc_name 字段",
        "score": "综合得分分值",
        "helpful": "rag_feedback 表的 helpful 字段",
        "note": "版本备注说明",
        "created_at": "记录创建时间（东八区）"
    },
    "knowledge_entities": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "name": "名称",
        "normalized_name": "knowledge_entities 表的 normalized_name 字段",
        "type": "类型标识",
        "description": "详细描述说明",
        "aliases": "同义别名列表（JSON）",
        "confidence": "置信度得分（0.0~1.0）",
        "source_doc_id": "knowledge_entities 表的 source_doc_id 字段",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）",
        "deleted_at": "软删除时间（为空表示正常有效）"
    },
    "knowledge_entity_mentions": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "entity_id": "knowledge_entity_mentions 表的 entity_id 字段",
        "doc_id": "所属知识库文档 ID（关联 knowledge_docs.id）",
        "chunk_id": "knowledge_entity_mentions 表的 chunk_id 字段",
        "snippet": "knowledge_entity_mentions 表的 snippet 字段",
        "created_at": "记录创建时间（东八区）"
    },
    "knowledge_relations": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "source_entity_id": "knowledge_relations 表的 source_entity_id 字段",
        "target_entity_id": "knowledge_relations 表的 target_entity_id 字段",
        "relation_type": "关系谓词类型",
        "description": "详细描述说明",
        "confidence": "置信度得分（0.0~1.0）",
        "source_doc_id": "knowledge_relations 表的 source_doc_id 字段",
        "source_chunk_id": "knowledge_relations 表的 source_chunk_id 字段",
        "status": "状态标识",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "attachments": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "session_id": "关联的会话 ID（关联 sessions.id）",
        "file_name": "attachments 表的 file_name 字段",
        "file_path": "文件磁盘存储物理相对路径",
        "file_type": "文件类型后缀",
        "file_size": "文件大小（字节）",
        "access_token": "attachments 表的 access_token 字段",
        "expires_at": "过期失效时间",
        "deleted_at": "软删除时间（为空表示正常有效）",
        "deleted_by_user": "执行删除操作的用户 ID",
        "created_at": "记录创建时间（东八区）"
    },
    "document_files": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "original_name": "文件原始名称",
        "stored_name": "document_files 表的 stored_name 字段",
        "file_path": "文件磁盘存储物理相对路径",
        "file_type": "文件类型后缀",
        "file_ext": "document_files 表的 file_ext 字段",
        "file_size": "文件大小（字节）",
        "page_count": "document_files 表的 page_count 字段",
        "source_module": "document_files 表的 source_module 字段",
        "source_ref": "来源引用标识",
        "sha256": "SHA-256 唯一校验哈希",
        "metadata_json": "扩展元数据结构体（JSON）",
        "deleted_at": "软删除时间（为空表示正常有效）",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "document_jobs": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "file_id": "关联的文档文件 ID（关联 document_files.id）",
        "job_type": "document_jobs 表的 job_type 字段",
        "status": "状态标识",
        "progress": "任务执行进度百分比（0~100）",
        "error_message": "异常报错信息",
        "config_json": "配置参数结构体（JSON）",
        "result_json": "document_jobs 表的 result_json 字段",
        "attempts": "已重试次数",
        "max_attempts": "最大允许重试次数",
        "locked_at": "任务加锁时间（防止并发争抢）",
        "cancelled_at": "document_jobs 表的 cancelled_at 字段",
        "completed_at": "执行完成时间",
        "source_module": "document_jobs 表的 source_module 字段",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "document_pages": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "file_id": "关联的文档文件 ID（关联 document_files.id）",
        "job_id": "关联的文档作业 ID（关联 document_jobs.id）",
        "page_number": "document_pages 表的 page_number 字段",
        "width": "document_pages 表的 width 字段",
        "height": "document_pages 表的 height 字段",
        "image_path": "图片文件存储路径",
        "text": "识别出的文本内容",
        "text_length": "document_pages 表的 text_length 字段",
        "ocr_status": "document_pages 表的 ocr_status 字段",
        "confidence": "置信度得分（0.0~1.0）",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "document_ocr_blocks": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "file_id": "关联的文档文件 ID（关联 document_files.id）",
        "job_id": "关联的文档作业 ID（关联 document_jobs.id）",
        "page_id": "关联的文档页面 ID（关联 document_pages.id）",
        "page_number": "document_ocr_blocks 表的 page_number 字段",
        "sort_order": "document_ocr_blocks 表的 sort_order 字段",
        "block_type": "OCR 文本块类型",
        "text": "识别出的文本内容",
        "bbox_json": "document_ocr_blocks 表的 bbox_json 字段",
        "confidence": "置信度得分（0.0~1.0）",
        "language": "document_ocr_blocks 表的 language 字段",
        "engine": "document_ocr_blocks 表的 engine 字段",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "document_outputs": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "file_id": "关联的文档文件 ID（关联 document_files.id）",
        "job_id": "关联的文档作业 ID（关联 document_jobs.id）",
        "output_type": "document_outputs 表的 output_type 字段",
        "file_path": "文件磁盘存储物理相对路径",
        "file_name": "document_outputs 表的 file_name 字段",
        "mime_type": "MIME 媒体类型（如 application/pdf）",
        "file_size": "文件大小（字节）",
        "status": "状态标识",
        "expires_at": "过期失效时间",
        "created_at": "记录创建时间（东八区）"
    },
    "document_reviews": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "file_id": "关联的文档文件 ID（关联 document_files.id）",
        "job_id": "关联的文档作业 ID（关联 document_jobs.id）",
        "page_id": "关联的文档页面 ID（关联 document_pages.id）",
        "review_status": "document_reviews 表的 review_status 字段",
        "original_text": "document_reviews 表的 original_text 字段",
        "revised_text": "document_reviews 表的 revised_text 字段",
        "low_confidence_confirmed": "document_reviews 表的 low_confidence_confirmed 字段",
        "reviewed_at": "document_reviews 表的 reviewed_at 字段",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "prompts": {
        "id": "主键自增 ID / 唯一主键",
        "name": "名称",
        "content": "正文内容",
        "category": "业务分类类别",
        "description": "详细描述说明",
        "type": "类型标识",
        "target_surfaces": "适用界面（chat,agent,workflow）",
        "user_id": "所属用户 ID（关联 users.id）",
        "scope": "可见范围或作用域（public/unit/private/system）",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "refresh_tokens": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "token": "刷新令牌 Token 密文",
        "expires_at": "过期失效时间",
        "created_at": "记录创建时间（东八区）"
    },
    "api_keys": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "name": "名称",
        "key_hash": "API Key 哈希密文",
        "key_preview": "api_keys 表的 key_preview 字段",
        "key": "唯一标识 Key",
        "status": "状态标识",
        "usage_tokens": "api_keys 表的 usage_tokens 字段",
        "input_tokens": "api_keys 表的 input_tokens 字段",
        "output_tokens": "api_keys 表的 output_tokens 字段",
        "last_used_at": "最后一次使用/命中时间",
        "created_at": "记录创建时间（东八区）"
    },
    "model_usage_events": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "model_id": "关联的模型 ID（关联 models.id）",
        "source": "model_usage_events 表的 source 字段",
        "token_count": "Token 数量统计",
        "input_tokens": "model_usage_events 表的 input_tokens 字段",
        "output_tokens": "model_usage_events 表的 output_tokens 字段",
        "created_at": "记录创建时间（东八区）"
    },
    "api_call_logs": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "api_key_id": "api_call_logs 表的 api_key_id 字段",
        "model_id": "关联的模型 ID（关联 models.id）",
        "model_name": "api_call_logs 表的 model_name 字段",
        "request_messages": "api_call_logs 表的 request_messages 字段",
        "response_text": "api_call_logs 表的 response_text 字段",
        "status": "状态标识",
        "error_message": "异常报错信息",
        "input_tokens": "api_call_logs 表的 input_tokens 字段",
        "output_tokens": "api_call_logs 表的 output_tokens 字段",
        "total_tokens": "api_call_logs 表的 total_tokens 字段",
        "stream": "api_call_logs 表的 stream 字段",
        "ip_address": "客户端 IP 地址",
        "created_at": "记录创建时间（东八区）"
    },
    "agent_runs": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "session_id": "关联的会话 ID（关联 sessions.id）",
        "model_id": "关联的模型 ID（关联 models.id）",
        "title": "标题",
        "goal": "目标需求描述",
        "status": "状态标识",
        "final_answer": "智能体最终交付回答总结",
        "error_message": "异常报错信息",
        "max_steps": "最大允许轮数步数",
        "parent_run_id": "agent_runs 表的 parent_run_id 字段",
        "priority": "优先级数值",
        "run_mode": "运行模式",
        "tool_policy": "agent_runs 表的 tool_policy 字段",
        "tool_allowlist": "agent_runs 表的 tool_allowlist 字段",
        "approval_policy": "agent_runs 表的 approval_policy 字段",
        "timeout_ms": "agent_runs 表的 timeout_ms 字段",
        "tool_timeout_ms": "agent_runs 表的 tool_timeout_ms 字段",
        "retry_limit": "agent_runs 表的 retry_limit 字段",
        "retry_count": "agent_runs 表的 retry_count 字段",
        "max_token_budget": "agent_runs 表的 max_token_budget 字段",
        "export_count": "agent_runs 表的 export_count 字段",
        "template_id": "关联的模版 ID（关联 agent_templates.id）",
        "schedule_id": "关联的调度任务 ID（关联 agent_schedules.id）",
        "dedupe_key": "agent_runs 表的 dedupe_key 字段",
        "context_config": "agent_runs 表的 context_config 字段",
        "resume_from_step": "agent_runs 表的 resume_from_step 字段",
        "metadata": "扩展元数据结构体（JSON）",
        "model_router": "agent_runs 表的 model_router 字段",
        "chosen_model_id": "agent_runs 表的 chosen_model_id 字段",
        "started_at": "开始执行时间",
        "last_heartbeat_at": "agent_runs 表的 last_heartbeat_at 字段",
        "locked_by": "agent_runs 表的 locked_by 字段",
        "lock_expires_at": "agent_runs 表的 lock_expires_at 字段",
        "input_tokens": "agent_runs 表的 input_tokens 字段",
        "output_tokens": "agent_runs 表的 output_tokens 字段",
        "total_tokens": "agent_runs 表的 total_tokens 字段",
        "cancelled_at": "agent_runs 表的 cancelled_at 字段",
        "deleted_at": "软删除时间（为空表示正常有效）",
        "deleted_by_user": "执行删除操作的用户 ID",
        "delete_reason": "agent_runs 表的 delete_reason 字段",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）",
        "completed_at": "执行完成时间"
    },
    "agent_steps": {
        "id": "主键自增 ID / 唯一主键",
        "run_id": "所属智能体任务运行 ID（关联 agent_runs.id）",
        "step_index": "agent_steps 表的 step_index 字段",
        "type": "类型标识",
        "title": "标题",
        "tool_name": "调用的工具名称",
        "input": "输入参数或 Prompt 数据",
        "output": "agent_steps 表的 output 字段",
        "error_message": "异常报错信息",
        "status": "状态标识",
        "duration_ms": "耗时时长（毫秒）",
        "started_at": "开始执行时间",
        "completed_at": "执行完成时间",
        "created_at": "记录创建时间（东八区）"
    },
    "agent_traces": {
        "run_id": "所属智能体任务运行 ID（关联 agent_runs.id）",
        "user_id": "所属用户 ID（关联 users.id）",
        "status": "状态标识",
        "metadata": "扩展元数据结构体（JSON）",
        "started_at": "开始执行时间",
        "completed_at": "执行完成时间",
        "duration_ms": "耗时时长（毫秒）",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "agent_trace_spans": {
        "id": "主键自增 ID / 唯一主键",
        "span_id": "链路 SpanId",
        "run_id": "所属智能体任务运行 ID（关联 agent_runs.id）",
        "parent_span_id": "父级链路 SpanId",
        "span_type": "agent_trace_spans 表的 span_type 字段",
        "name": "名称",
        "status": "状态标识",
        "input_summary": "agent_trace_spans 表的 input_summary 字段",
        "output_summary": "agent_trace_spans 表的 output_summary 字段",
        "details": "详细信息明细",
        "error_message": "异常报错信息",
        "input_tokens": "agent_trace_spans 表的 input_tokens 字段",
        "output_tokens": "agent_trace_spans 表的 output_tokens 字段",
        "started_at": "开始执行时间",
        "completed_at": "执行完成时间",
        "duration_ms": "耗时时长（毫秒）",
        "created_at": "记录创建时间（东八区）"
    },
    "agent_run_checkpoints": {
        "id": "主键自增 ID / 唯一主键",
        "run_id": "所属智能体任务运行 ID（关联 agent_runs.id）",
        "step_index": "agent_run_checkpoints 表的 step_index 字段",
        "status": "状态标识",
        "state": "运行时状态快照（JSON）",
        "created_at": "记录创建时间（东八区）"
    },
    "agent_eval_suites": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "name": "名称",
        "description": "详细描述说明",
        "target_type": "通知面向的主体类型",
        "workflow_id": "所属工作流 ID（关联 agent_workflows.id）",
        "workflow_version": "agent_eval_suites 表的 workflow_version 字段",
        "model_id": "关联的模型 ID（关联 models.id）",
        "run_config": "agent_eval_suites 表的 run_config 字段",
        "status": "状态标识",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）",
        "deleted_at": "软删除时间（为空表示正常有效）"
    },
    "agent_eval_cases": {
        "id": "主键自增 ID / 唯一主键",
        "suite_id": "所属评测集 ID（关联 agent_eval_suites.id）",
        "name": "名称",
        "input": "输入参数或 Prompt 数据",
        "input_variables": "agent_eval_cases 表的 input_variables 字段",
        "expected_output": "期望的标准参考答案",
        "assertions": "agent_eval_cases 表的 assertions 字段",
        "sort_order": "agent_eval_cases 表的 sort_order 字段",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）",
        "deleted_at": "软删除时间（为空表示正常有效）"
    },
    "agent_eval_runs": {
        "id": "主键自增 ID / 唯一主键",
        "suite_id": "所属评测集 ID（关联 agent_eval_suites.id）",
        "user_id": "所属用户 ID（关联 users.id）",
        "status": "状态标识",
        "target_snapshot": "agent_eval_runs 表的 target_snapshot 字段",
        "summary": "内容摘要总结",
        "started_at": "开始执行时间",
        "completed_at": "执行完成时间",
        "created_at": "记录创建时间（东八区）"
    },
    "agent_eval_results": {
        "id": "主键自增 ID / 唯一主键",
        "eval_run_id": "agent_eval_results 表的 eval_run_id 字段",
        "case_id": "关联的评测用例 ID（关联 agent_eval_cases.id）",
        "agent_run_id": "agent_eval_results 表的 agent_run_id 字段",
        "status": "状态标识",
        "score": "综合得分分值",
        "passed": "agent_eval_results 表的 passed 字段",
        "grader_results": "agent_eval_results 表的 grader_results 字段",
        "actual_output": "模型实际生成回答内容",
        "error_message": "异常报错信息",
        "duration_ms": "耗时时长（毫秒）",
        "total_tokens": "agent_eval_results 表的 total_tokens 字段",
        "created_at": "记录创建时间（东八区）",
        "completed_at": "执行完成时间"
    },
    "agent_templates": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "scope": "可见范围或作用域（public/unit/private/system）",
        "name": "名称",
        "description": "详细描述说明",
        "goal_template": "目标提示词模板",
        "run_mode": "运行模式",
        "tool_policy": "agent_templates 表的 tool_policy 字段",
        "tool_allowlist": "agent_templates 表的 tool_allowlist 字段",
        "approval_policy": "agent_templates 表的 approval_policy 字段",
        "max_steps": "最大允许轮数步数",
        "max_token_budget": "agent_templates 表的 max_token_budget 字段",
        "retry_limit": "agent_templates 表的 retry_limit 字段",
        "context_config": "agent_templates 表的 context_config 字段",
        "allowed_units": "允许访问的单位/部门白名单（JSON）",
        "model_router": "agent_templates 表的 model_router 字段",
        "dag_spec": "agent_templates 表的 dag_spec 字段",
        "dag_inputs": "agent_templates 表的 dag_inputs 字段",
        "workflow_id": "所属工作流 ID（关联 agent_workflows.id）",
        "workflow_version": "agent_templates 表的 workflow_version 字段",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）",
        "deleted_at": "软删除时间（为空表示正常有效）"
    },
    "agent_schedules": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "template_id": "关联的模版 ID（关联 agent_templates.id）",
        "model_id": "关联的模型 ID（关联 models.id）",
        "name": "名称",
        "goal": "目标需求描述",
        "frequency": "agent_schedules 表的 frequency 字段",
        "time_of_day": "agent_schedules 表的 time_of_day 字段",
        "day_of_week": "agent_schedules 表的 day_of_week 字段",
        "interval_minutes": "agent_schedules 表的 interval_minutes 字段",
        "cron_expression": "标准 Cron 调度表达式",
        "status": "状态标识",
        "run_config": "agent_schedules 表的 run_config 字段",
        "next_run_at": "预计下次调度执行时间",
        "last_run_at": "最后一次触发运行时间",
        "last_run_id": "agent_schedules 表的 last_run_id 字段",
        "claim_token": "agent_schedules 表的 claim_token 字段",
        "claim_expires_at": "agent_schedules 表的 claim_expires_at 字段",
        "dispatch_failures": "agent_schedules 表的 dispatch_failures 字段",
        "dispatch_retry_at": "agent_schedules 表的 dispatch_retry_at 字段",
        "last_error": "最后一次失败错误原因",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）",
        "deleted_at": "软删除时间（为空表示正常有效）"
    },
    "agent_workflows": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "name": "名称",
        "description": "详细描述说明",
        "scope": "可见范围或作用域（public/unit/private/system）",
        "allowed_units": "允许访问的单位/部门白名单（JSON）",
        "allowed_user_ids": "允许访问的用户 ID 白名单（JSON）",
        "current_version_id": "当前激活的版本 ID",
        "published_version_id": "agent_workflows 表的 published_version_id 字段",
        "published_at": "agent_workflows 表的 published_at 字段",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）",
        "deleted_at": "软删除时间（为空表示正常有效）"
    },
    "agent_workflow_versions": {
        "id": "主键自增 ID / 唯一主键",
        "workflow_id": "所属工作流 ID（关联 agent_workflows.id）",
        "version": "版本号标识",
        "dag_spec": "agent_workflow_versions 表的 dag_spec 字段",
        "note": "版本备注说明",
        "created_by": "创建人用户 ID（关联 users.id）",
        "created_at": "记录创建时间（东八区）"
    },
    "agent_workflow_dependency_bindings": {
        "id": "主键自增 ID / 唯一主键",
        "workflow_id": "所属工作流 ID（关联 agent_workflows.id）",
        "user_id": "所属用户 ID（关联 users.id）",
        "published_version_id": "agent_workflow_dependency_bindings 表的 published_version_id 字段",
        "bindings_json": "agent_workflow_dependency_bindings 表的 bindings_json 字段",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "agent_workflow_triggers": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "workflow_id": "所属工作流 ID（关联 agent_workflows.id）",
        "name": "名称",
        "trigger_type": "触发器类型",
        "token_hash": "agent_workflow_triggers 表的 token_hash 字段",
        "token_hint": "agent_workflow_triggers 表的 token_hint 字段",
        "status": "状态标识",
        "config_json": "配置参数结构体（JSON）",
        "watermark": "agent_workflow_triggers 表的 watermark 字段",
        "last_triggered_at": "agent_workflow_triggers 表的 last_triggered_at 字段",
        "last_run_id": "agent_workflow_triggers 表的 last_run_id 字段",
        "trigger_count": "agent_workflow_triggers 表的 trigger_count 字段",
        "last_error": "最后一次失败错误原因",
        "claim_token": "agent_workflow_triggers 表的 claim_token 字段",
        "claim_expires_at": "agent_workflow_triggers 表的 claim_expires_at 字段",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）",
        "deleted_at": "软删除时间（为空表示正常有效）"
    },
    "workflow_credentials": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "name": "名称",
        "slug": "URL 友好别名 Slug",
        "description": "详细描述说明",
        "secret_value": "workflow_credentials 表的 secret_value 字段",
        "scope": "可见范围或作用域（public/unit/private/system）",
        "allowed_units": "允许访问的单位/部门白名单（JSON）",
        "version": "版本号标识",
        "previous_value": "workflow_credentials 表的 previous_value 字段",
        "previous_expires_at": "workflow_credentials 表的 previous_expires_at 字段",
        "last_used_at": "最后一次使用/命中时间",
        "use_count": "凭证被调用使用累计次数",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）",
        "deleted_at": "软删除时间（为空表示正常有效）"
    },
    "agent_artifacts": {
        "id": "主键自增 ID / 唯一主键",
        "run_id": "所属智能体任务运行 ID（关联 agent_runs.id）",
        "user_id": "所属用户 ID（关联 users.id）",
        "type": "类型标识",
        "title": "标题",
        "content": "正文内容",
        "current_version_id": "当前激活的版本 ID",
        "note": "版本备注说明",
        "updated_at": "最后更新时间（东八区）",
        "created_at": "记录创建时间（东八区）"
    },
    "agent_artifact_versions": {
        "id": "主键自增 ID / 唯一主键",
        "artifact_id": "关联的产物 ID（关联 agent_artifacts.id）",
        "version": "版本号标识",
        "content": "正文内容",
        "note": "版本备注说明",
        "created_by": "创建人用户 ID（关联 users.id）",
        "created_at": "记录创建时间（东八区）"
    },
    "agent_dag_nodes": {
        "id": "主键自增 ID / 唯一主键",
        "run_id": "所属智能体任务运行 ID（关联 agent_runs.id）",
        "node_key": "节点唯一标识 Key",
        "title": "标题",
        "tool_name": "调用的工具名称",
        "input": "输入参数或 Prompt 数据",
        "input_schema": "入参 JSON Schema 定义",
        "output_schema": "出参 JSON Schema 定义",
        "depends_on": "依赖的上游节点列表（JSON）",
        "condition": "分支执行判断条件表达式",
        "status": "状态标识",
        "output": "agent_dag_nodes 表的 output 字段",
        "error_message": "异常报错信息",
        "contract_status": "agent_dag_nodes 表的 contract_status 字段",
        "contract_issues": "agent_dag_nodes 表的 contract_issues 字段",
        "attempt_count": "执行尝试重试次数",
        "duration_ms": "耗时时长（毫秒）",
        "created_at": "记录创建时间（东八区）",
        "started_at": "开始执行时间",
        "completed_at": "执行完成时间"
    },
    "agent_approval_requests": {
        "id": "主键自增 ID / 唯一主键",
        "run_id": "所属智能体任务运行 ID（关联 agent_runs.id）",
        "user_id": "所属用户 ID（关联 users.id）",
        "request_type": "请求业务类型",
        "node_key": "节点唯一标识 Key",
        "approval_key": "审批唯一标识 Key",
        "title": "标题",
        "summary": "内容摘要总结",
        "instructions": "审批操作指引说明",
        "status": "状态标识",
        "current_level": "当前审批层级序号",
        "required_levels": "总计需要的审批层级数",
        "levels_json": "多级审批层级配置（JSON）",
        "decisions_json": "各层级审批裁决历史（JSON）",
        "input_json": "敏感操作入参载荷（JSON）",
        "callback_token_hash": "回调令牌哈希值",
        "callback_token_hint": "回调令牌安全提示",
        "callback_nonce": "回调防重放随机数 Nonce",
        "callback_credential_slug": "回调授权凭证别名",
        "callback_signature_required": "回调是否要求强制签名验证（1:是, 0:否）",
        "timeout_action": "审批超时动作策略（reject/escalate）",
        "expires_at": "过期失效时间",
        "decided_at": "审批决定签署时间",
        "decided_by": "裁决人用户 ID",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "agent_notifications": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "run_id": "所属智能体任务运行 ID（关联 agent_runs.id）",
        "type": "类型标识",
        "title": "标题",
        "body": "通知详细正文内容",
        "status": "状态标识",
        "read_at": "消息/通知已读时间",
        "created_at": "记录创建时间（东八区）"
    },
    "announcements": {
        "id": "主键自增 ID / 唯一主键",
        "title": "标题",
        "content": "正文内容",
        "type": "类型标识",
        "priority": "优先级数值",
        "target_type": "通知面向的主体类型",
        "target_value": "通知面向的主体标识值",
        "require_ack": "是否强制要求确认知晓（1:是, 0:否）",
        "show_on_login": "登录时是否强行弹窗展示（1:是, 0:否）",
        "starts_at": "生效开始时间",
        "ends_at": "生效结束时间",
        "status": "状态标识",
        "created_by": "创建人用户 ID（关联 users.id）",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）",
        "deleted_at": "软删除时间（为空表示正常有效）"
    },
    "announcement_reads": {
        "announcement_id": "announcement_reads 表的 announcement_id 字段",
        "user_id": "所属用户 ID（关联 users.id）",
        "read_at": "消息/通知已读时间",
        "acknowledged_at": "确认/知晓处理时间",
        "dismissed_at": "忽略/关闭时间"
    },
    "mcp_servers": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "name": "名称",
        "base_url": "服务基础 URL 地址",
        "api_key": "API 密钥凭证（加密存储）",
        "description": "详细描述说明",
        "config": "配置参数结构体（JSON）",
        "scope": "可见范围或作用域（public/unit/private/system）",
        "allowed_units": "允许访问的单位/部门白名单（JSON）",
        "allowed_user_ids": "允许访问的用户 ID 白名单（JSON）",
        "status": "状态标识",
        "last_error": "最后一次失败错误原因",
        "last_checked_at": "最后一次健康巡检时间",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "mcp_tool_cache": {
        "id": "主键自增 ID / 唯一主键",
        "server_id": "所属 MCP 服务节点 ID（关联 mcp_servers.id）",
        "name": "名称",
        "description": "详细描述说明",
        "input_schema": "入参 JSON Schema 定义",
        "cached_at": "mcp_tool_cache 表的 cached_at 字段"
    },
    "mcp_call_logs": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "server_id": "所属 MCP 服务节点 ID（关联 mcp_servers.id）",
        "tool_name": "调用的工具名称",
        "source": "mcp_call_logs 表的 source 字段",
        "status": "状态标识",
        "duration_ms": "耗时时长（毫秒）",
        "input_preview": "入参快照预览",
        "output_preview": "出参快照预览",
        "error_message": "异常报错信息",
        "created_at": "记录创建时间（东八区）"
    },
    "mcp_database_connections": {
        "id": "主键自增 ID / 唯一主键",
        "mcp_server_id": "关联的 MCP 服务节点 ID",
        "user_id": "所属用户 ID（关联 users.id）",
        "database_type": "数据库引擎类型（mysql/postgresql/mssql 等）",
        "host": "主机地址 IP 或域名",
        "port": "端口号",
        "database_name": "数据库名称/实例名",
        "username": "登录用户名",
        "password": "数据库密码（加密存储）",
        "options": "高级连接选项配置（JSON）",
        "status": "状态标识",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "mcp_builtin_configs": {
        "id": "主键自增 ID / 唯一主键",
        "mcp_server_id": "关联的 MCP 服务节点 ID",
        "user_id": "所属用户 ID（关联 users.id）",
        "service_type": "服务驱动类型",
        "config": "配置参数结构体（JSON）",
        "secret": "机密密钥/凭证",
        "status": "状态标识",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "analysis_datasets": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "name": "名称",
        "original_name": "文件原始名称",
        "file_type": "文件类型后缀",
        "file_size": "文件大小（字节）",
        "source_path": "源文件存储相对路径",
        "parquet_path": "高性能 Parquet 转换文件存储路径",
        "row_count": "行数统计",
        "column_count": "列数统计",
        "columns_json": "字段列结构定义（JSON）",
        "profile_json": "数据分布画像结构体（JSON）",
        "preview_json": "数据预览快照结构体（JSON）",
        "sheet_name": "Excel 工作表名称",
        "status": "状态标识",
        "error_message": "异常报错信息",
        "deleted_at": "软删除时间（为空表示正常有效）",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "analysis_artifacts": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "dataset_id": "关联的数据集 ID（关联 analysis_datasets.id）",
        "type": "类型标识",
        "title": "标题",
        "content": "正文内容",
        "file_path": "文件磁盘存储物理相对路径",
        "metadata_json": "扩展元数据结构体（JSON）",
        "created_at": "记录创建时间（东八区）"
    },
    "capability_packages": {
        "id": "主键自增 ID / 唯一主键",
        "package_key": "能力包唯一标识 Key",
        "type": "类型标识",
        "source_ref": "来源引用标识",
        "user_id": "所属用户 ID（关联 users.id）",
        "scope": "可见范围或作用域（public/unit/private/system）",
        "name": "名称",
        "description": "详细描述说明",
        "status": "状态标识",
        "config": "配置参数结构体（JSON）",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "observability_events": {
        "id": "主键自增 ID / 唯一主键",
        "type": "类型标识",
        "source": "observability_events 表的 source 字段",
        "severity": "严重等级（info/warn/error/critical）",
        "duration_ms": "耗时时长（毫秒）",
        "threshold_ms": "超限告警阈值（毫秒）",
        "message": "日志消息正文",
        "details": "详细信息明细",
        "status": "状态标识",
        "alerted_at": "触发报警通知时间",
        "acknowledged_at": "确认/知晓处理时间",
        "created_at": "记录创建时间（东八区）"
    },
    "rag_debug_queries": {
        "id": "主键自增 ID / 唯一主键",
        "user_id": "所属用户 ID（关联 users.id）",
        "query": "rag_debug_queries 表的 query 字段",
        "scope_json": "检索范围限定配置（JSON）",
        "top_k": "召回 Top-K 数量上限",
        "candidate_limit": "初筛候选集数量限制",
        "score_threshold": "相似度得分过滤阈值",
        "candidate_count": "初筛命中的候选分块数",
        "matched_count": "最终采纳匹配的分块数",
        "selected_chunk_ids": "最终选中的分块 ID 列表（JSON）",
        "scores_json": "分块得分明细（JSON）",
        "queue_json": "检索排队与耗时指标（JSON）",
        "elapsed_ms": "经过时长（毫秒）",
        "created_at": "记录创建时间（东八区）"
    },
    "organizations": {
        "id": "主键自增 ID / 唯一主键",
        "name": "名称",
        "slug": "URL 友好别名 Slug",
        "status": "状态标识",
        "metadata_json": "扩展元数据结构体（JSON）",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "teams": {
        "id": "主键自增 ID / 唯一主键",
        "organization_id": "所属企业组织 ID（关联 organizations.id）",
        "name": "名称",
        "slug": "URL 友好别名 Slug",
        "status": "状态标识",
        "metadata_json": "扩展元数据结构体（JSON）",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "team_members": {
        "id": "主键自增 ID / 唯一主键",
        "team_id": "所属团队部门 ID（关联 teams.id）",
        "user_id": "所属用户 ID（关联 users.id）",
        "role": "角色标识（user/assistant/system/tool 等）",
        "status": "状态标识",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "resource_permissions": {
        "id": "主键自增 ID / 唯一主键",
        "subject_type": "被授权主体类型（user/team/org/role）",
        "subject_id": "被授权主体 ID",
        "resource_type": "资源分类（knowledge/workflow/model/agent）",
        "resource_id": "资源唯一标识 ID",
        "action": "操作动作权限",
        "effect": "授权效果（allow允许/deny拒绝）",
        "conditions_json": "ABAC 动态属性判断条件（JSON）",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "policy_objects": {
        "id": "主键自增 ID / 唯一主键",
        "organization_id": "所属企业组织 ID（关联 organizations.id）",
        "owner_user_id": "所有者用户 ID（关联 users.id）",
        "object_type": "策略管控对象类型",
        "object_id": "策略管控对象 ID",
        "classification": "数据安全密级分类（public/internal/confidential/secret）",
        "policy_json": "合规策略规则表达式（JSON）",
        "status": "状态标识",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    },
    "deployment_provider_configs": {
        "id": "主键自增 ID / 唯一主键",
        "provider_type": "服务商接入类型（local/cloud/vpc）",
        "provider_key": "算力服务商唯一标识 Key",
        "status": "状态标识",
        "config_json": "配置参数结构体（JSON）",
        "health_json": "服务商健康度监测数据（JSON）",
        "last_checked_at": "最后一次健康巡检时间",
        "created_at": "记录创建时间（东八区）",
        "updated_at": "最后更新时间（东八区）"
    }
};

/**
 * 生成全量 PostgreSQL COMMENT ON 语句列表
 */
function buildPgCommentStatements() {
    const statements = [];

    // 1. 表级注释
    for (const [table, comment] of Object.entries(TABLE_COMMENTS)) {
        statements.push(`COMMENT ON TABLE "${table}" IS '${comment.replace(/'/g, "''")}';`);
    }

    // 2. 字段级注释
    for (const [table, cols] of Object.entries(COLUMN_COMMENTS)) {
        for (const [col, comment] of Object.entries(cols)) {
            statements.push(`COMMENT ON COLUMN "${table}"."${col}" IS '${comment.replace(/'/g, "''")}';`);
        }
    }

    return statements;
}

module.exports = {
    TABLE_COMMENTS,
    COLUMN_COMMENTS,
    buildPgCommentStatements,
};
