const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

test('知识 Wiki 路由、问答融合和工作台入口保持来源优先契约', () => {
    const root = path.resolve(__dirname, '..');
    const route = fs.readFileSync(path.join(root, 'server/routes/knowledge.js'), 'utf8');
    const service = fs.readFileSync(path.join(root, 'server/services/knowledge-wiki.js'), 'utf8');
    const shell = fs.readFileSync(path.join(root, 'client/chat/partials/workspaces/knowledge.html'), 'utf8');
    const scripts = fs.readFileSync(path.join(root, 'client/chat/partials/scripts.html'), 'utf8');
    assert.match(route, /\/knowledge\/wiki\/spaces/);
    assert.match(route, /\/knowledge\/wiki\/runs\/:id\/cancel/);
    assert.match(route, /retrieveWikiContext/);
    assert.match(route, /原始依据优先/);
    assert.match(service, /sourceRefs 只能引用输入中的/);
    assert.match(service, /待确认冲突/);
    assert.match(service, /createKnowledgeWikiCompileWorker/);
    assert.match(service, /cancelWikiCompileRun/);
    assert.match(service, /document\.current_version_id <> source\.version_id/);
    assert.match(shell, /id="knowledge-wiki-open"/);
    assert.match(scripts, /knowledge-wiki\.js/);
    const wikiClient = fs.readFileSync(path.join(root, 'client/chat/knowledge-wiki.js'), 'utf8');
    assert.match(wikiClient, /openWikiSetupForm/);
    assert.match(wikiClient, /knowledge-wiki-setup-form/);
    assert.match(wikiClient, /model-selector/);
    assert.doesNotMatch(wikiClient, /window\.prompt/);
    const autoRoute = fs.readFileSync(path.join(root, 'client/chat/chat-auto-route.js'), 'utf8');
    const product = fs.readFileSync(path.join(root, 'client/chat/knowledge-product.js'), 'utf8');
    assert.match(autoRoute, /wikiSpaces/);
    assert.match(autoRoute, /Wiki 综合/);
    assert.match(autoRoute, /collections: active\.filter[\s\S]*collectionId/);
    assert.match(product, /renderWikiPages/);
    assert.match(product, /Wiki 综合（原始依据优先）/);
    const sourceService = fs.readFileSync(path.join(root, 'server/services/knowledge-sources.js'), 'utf8');
    const wikiMarkdown = fs.readFileSync(path.join(root, 'server/services/knowledge-wiki-markdown.js'), 'utf8');
    assert.match(sourceService, /wiki_markdown/);
    assert.match(wikiMarkdown, /parseMarkdownFrontmatter/);
    assert.match(wikiMarkdown, /不写回源目录/);
});
